services:
  web:
    build: .
    container_name: tc-api-container-dev
    image: tc-api-image-dev
    command: /srv/start
    volumes:
      - .:/code
      - ../taicol-volumes/static:/code/conf/static
      - ../tc-web-volumes/solr:/var/solr
    ports:
      - 8005:8005
    env_file:
      - .env
    restart: always
