networks:
  gateway:
    external: true
  traefik-api:
    external: true

services:
  web:
    build: .
    container_name: tc-api-container
    image: tc-api-image
    command: /srv/start
    volumes:
      - .:/code
      - ../taicol-volumes/static:/code/conf/static
    expose:
      - 8002
    env_file:
      - .env
    networks:
      - gateway
      - traefik-api
  nginx-api:
    image: nginx:1.19.10-alpine
    container_name: nginx-api
    restart: always
    volumes:
      - ./scripts/nginx/production:/etc/nginx/conf.d
      - ../tc-web-volumes/logs/nginx-api:/var/log/nginx
    networks:
      - traefik-api
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx-api.rule=Host(`api.taicol.tw`)"
      - "traefik.http.routers.nginx-api.entrypoints=websecure"
      - "traefik.http.routers.nginx-api.tls.certresolver=myresolver"
      - "traefik.http.routers.nginx-api.middlewares=ratelimit-api"
      - "traefik.http.middlewares.ratelimit-api.ratelimit.average=8"
      - "traefik.http.middlewares.ratelimit-api.ratelimit.burst=10"