version: '3.7'

services:
  web:
    build: .
    container_name: tc-api-container
    image: tc-api-image
    command: /srv/start
    volumes:
      - .:/code
      - ../taicol-volumes/static:/code/conf/static
    ports:
      - 8002:8002
    tty: true
    stdin_open: true
    env_file:
      - .env

