version: '3.7'

services:
  web:
    build: .
    container_name: tc-api-container
    image: tc-api-image
    command: ./scripts/docker-entry.sh
    volumes:
      - .:/code
      - ../taicol-volumes/static:/code/conf/static
    expose:
      - 8001
    tty: true
    stdin_open: true
    env_file:
      - .env

  nginx:
    image: nginx
    restart: always
    ports:
      - 80:80
      # - 443:443
    volumes:
      - ./scripts/nginx-django.conf:/etc/nginx/conf.d/nginx-django.conf
      # - ./taicol-volumes/logs/nginx:/var/log/nginx
      - ../taicol-volumes/static:/code/conf/static
      # - ./taicol-volumes/certbot/conf:/etc/letsencrypt
      # - ./taicol-volumes/certbot/www:/var/www/certbot
    links:
      - web:web
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done &
      nginx -g \"daemon off;\"'"
