
version: '3.7'

services:
  web:
    build: .
    container_name: tc-api-container
    image: tc-api-image
    command: /srv/start
    volumes:
      - .:/code
      - ../taicol-volumes/static:/code/conf/static
      # - ../taicol-volumes/data:/code/data
    expose:
      - 8002
    tty: true
    stdin_open: true
    env_file:
      - .env
  nginx:
    image: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./scripts/nginx-django.conf:/etc/nginx/conf.d/nginx-django.conf
      # - ./taicol-volumes/logs/nginx:/var/log/nginx
      - ../taicol-volumes/static:/code/conf/static
      - ../taicol-volumes/certbot/conf:/etc/letsencrypt
      - ../taicol-volumes/certbot/www:/var/www/certbot
    links:
      - web:web
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done &
      nginx -g \"daemon off;\"'"
  mysql:
    build: ./scripts/mysql
    container_name: tc-api-mysql-container
    ports:
      - "3307:3306"
    image: tc-api-mysql-image
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    # env_file:
      # - ./app/.env
    volumes:
      - ../taicol-volumes/mysql:/var/lib/mysql:rw
      - ../taicol-volumes/bucket:/bucket
    command:
      [
        "mysqld",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]
  certbot:
    image: certbot/certbot
    volumes:
      - ../taicol-volumes/certbot/conf:/etc/letsencrypt
      - ../taicol-volumes/certbot/www:/var/www/certbot
