networks:
  gateway:
    external: true
  traefik-api:
    external: true

services:
  web:
    build: .
    container_name: tc-api-container
    image: tc-api-image
    command: /srv/start
    volumes:
      - .:/code
    expose:
      - 8002
    env_file:
      - .env
    networks:
      - gateway
  nginx-api:
    image: nginx:1.19.10-alpine
    container_name: nginx-api
    restart: always
    volumes:
      - ./scripts/nginx/staging:/etc/nginx/conf.d
    networks:
      - gateway
      - traefik-api
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx-web.rule=Host(`api-staging.taicol.tw`)"
      - "traefik.http.routers.nginx-web.entrypoints=websecure"
      - "traefik.http.routers.nginx-web.tls.certresolver=myresolver"
