version: '3.7'

services:
  web:
    build: .
    container_name: tc-api-container
    image: tc-api-image
    command: ./scripts/docker-entry.sh
    volumes:
      - .:/code
      - ../taicol-volumes/static:/code/conf/static
      # - ../taicol-volumes/data:/code/data
    ports:
      - 8002:8002
    tty: true
    stdin_open: true
    env_file:
      - .env
